linters-settings:
  gofmt:
    simplify: true  
  golint:
    enable-all: true
    min-confidence: 0.8
issues:
    exclude-use-default: false
    max-issues-per-linter: 0
linters:
  enable-all: true
  disable:
    - testpackage
    - dogsled